# Generated by Django 4.1.3 on 2023-01-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserveport',
            name='PE',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
