# Generated by Django 4.1.3 on 2023-01-07 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myint', '0002_alter_reserveport_pe'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservePort1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Router_Name', models.CharField(max_length=50)),
                ('newint', models.CharField(max_length=50)),
                ('Encapsulation', models.CharField(max_length=50)),
                ('newID', models.CharField(max_length=10)),
                ('Description', models.CharField(max_length=155)),
                ('IP', models.CharField(blank=True, max_length=35)),
                ('VLAN', models.IntegerField(validators=[django.core.validators.MinValueValidator(2300), django.core.validators.MaxValueValidator(2999)])),
                ('PE_vlan', models.CharField(blank=True, max_length=10)),
                ('User_type', models.CharField(max_length=20)),
                ('Rdate', models.DateField()),
                ('Rinfo', models.CharField(blank=True, max_length=25)),
            ],
        ),
    ]
