# Generated by Django 4.1.3 on 2023-01-08 05:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myint', '0003_reserveport1'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserveport1',
            name='Dayer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reserveport1',
            name='newID',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999999999)]),
        ),
    ]
