# Generated by Django 4.1.3 on 2023-01-27 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myint', '0005_alter_reserveport1_newid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserveport',
            name='Int',
        ),
    ]
