# Generated by Django 4.1.3 on 2023-01-28 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myint', '0007_reserveport1_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserveport',
            name='theauthor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
