# Generated by Django 4.1.3 on 2023-02-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myint', '0009_alter_reserveport_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserveport',
            name='Router',
            field=models.CharField(max_length=60),
        ),
    ]
